# Generated by Django 6.0.7 on 2026-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='theme',
            field=models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=10),
        ),
    ]
