# Generated by Django 6.0.7 on 2026-07-24 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('reservation', 'Réservation'), ('paiement', 'Paiement'), ('rappel', 'Rappel'), ('annulation', 'Annulation'), ('remboursement', 'Remboursement'), ('validation', 'Validation'), ('document_expire', 'Document expiré'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
