# Generated by Django 6.0.7 on 2026-08-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('reservation_confirmee', 'Réservation confirmée'), ('reservation_annulee', 'Réservation annulée'), ('reservation_remboursee', 'Réservation remboursée'), ('paiement_recu', 'Paiement reçu'), ('revenu_transfere', 'Revenu transféré'), ('remboursement_effectue', 'Remboursement effectué'), ('trajet_depart_confirme', 'Départ confirmé'), ('trajet_termine', 'Trajet terminé'), ('trajet_annule', 'Trajet annulé'), ('rappel_depart', 'Rappel de départ'), ('conducteur_valide', 'Dossier conducteur validé'), ('conducteur_rejete', 'Dossier conducteur rejeté'), ('conducteur_en_attente', 'Dossier en attente de validation'), ('vehicule_valide', 'Véhicule validé'), ('vehicule_rejete', 'Véhicule rejeté'), ('vehicule_suspendu', 'Véhicule suspendu'), ('vehicule_en_attente', 'Véhicule en attente de validation'), ('assurance_expiree', 'Assurance expirée'), ('assurance_bientot', 'Assurance bientôt expirée'), ('visite_expiree', 'Visite technique expirée'), ('visite_bientot', 'Visite technique bientôt expirée'), ('message_plateforme', 'Message de la plateforme'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
