# Generated by Django 6.0.7 on 2026-07-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteurs', '0003_alter_conducteur_options_conducteur_date_creation_and_more'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('duree_estimee', models.CharField(blank=True, max_length=20, null=True)),
                ('type_tarification', models.CharField(choices=[('unique', 'Tarif unique'), ('par_destination', 'Tarif par destination')], max_length=20)),
                ('prix_unique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.IntegerField()),
                ('politique_bagages', models.TextField(blank=True, null=True)),
                ('pauses_prevues', models.TextField(blank=True, null=True)),
                ('infos_complementaires', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='a_venir', max_length=20)),
                ('heure_depart_reelle', models.DateTimeField(blank=True, null=True)),
                ('heure_arrivee_reelle', models.DateTimeField(blank=True, null=True)),
                ('conducteur_remplacant', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='conducteurs.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='vehicules.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siege', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='trajets.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='PointArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_point', models.CharField(choices=[('ramassage', 'Ramassage'), ('depose', 'Dépose')], max_length=20)),
                ('nom_lieu', models.CharField(max_length=150)),
                ('ordre', models.IntegerField()),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_arret', to='trajets.trajet')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
