# Generated by Django 6.0.7 on 2026-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='est_chauffeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siege',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siege',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
