# Generated by Django 6.0.7 on 2026-08-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0002_siege_est_chauffeur_siege_pos_x_siege_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='lat_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='lat_depart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='lon_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='lon_depart',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
