# Generated by Django 6.0.7 on 2026-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0003_trajet_lat_arrivee_trajet_lat_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='duree_estimee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
