# Generated by Django 6.0.7 on 2026-07-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conducteur',
            old_name='photo_permis',
            new_name='permis_recto',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='statut',
            new_name='statut_validation',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='date_soumission',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='categorie_permis',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='cin_recto',
            field=models.ImageField(blank=True, null=True, upload_to='cin/'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='cin_verso',
            field=models.ImageField(blank=True, null=True, upload_to='cin/'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='contact_urgence_nom',
            field=models.CharField(default='Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='contact_urgence_telephone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='date_naissance',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='lieu_naissance',
            field=models.CharField(default='Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='note_moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='numero_cin',
            field=models.CharField(default='000000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='numero_mobile_money',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='operateur_mobile_money',
            field=models.CharField(choices=[('mvola', 'MVola'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money')], default='mvola', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='permis_verso',
            field=models.ImageField(blank=True, null=True, upload_to='permis/'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='titulaire_mobile_money',
            field=models.CharField(default='Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='numero_permis',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
