# Generated by Django 6.0.7 on 2026-07-22 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0002_rename_photo_permis_conducteur_permis_recto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conducteur',
            options={},
        ),
        migrations.AddField(
            model_name='conducteur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='categorie_permis',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='cin_recto',
            field=models.ImageField(upload_to='documents/cin/'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='cin_verso',
            field=models.ImageField(upload_to='documents/cin/'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='permis_recto',
            field=models.ImageField(upload_to='documents/permis/'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='permis_verso',
            field=models.ImageField(upload_to='documents/permis/'),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_conducteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
