# Generated by Django 6.0.7 on 2026-08-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0003_alter_conducteur_options_conducteur_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validation_conducteur', 'Validation conducteur'), ('rejet_conducteur', 'Rejet conducteur'), ('validation_vehicule', 'Validation véhicule'), ('rejet_vehicule', 'Rejet véhicule'), ('suspension_vehicule', 'Suspension véhicule'), ('confirmation_depart', 'Confirmation départ'), ('confirmation_fin', 'Confirmation fin trajet'), ('transfert_revenus', 'Transfert revenus')], max_length=50)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_admin', to=settings.AUTH_USER_MODEL)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actions', to='conducteurs.conducteur')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
