# Generated by Django 6.0.7 on 2026-07-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteurs', '0003_alter_conducteur_options_conducteur_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('taxi_brousse', 'Taxi-brousse'), ('voiture_privee', 'Voiture privée'), ('autocar', 'Autocar')], max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('couleur', models.CharField(max_length=30)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('nombre_places', models.IntegerField()),
                ('type_carburant', models.CharField(choices=[('diesel', 'Diesel'), ('essence', 'Essence')], max_length=20)),
                ('equipements', models.TextField(blank=True, null=True)),
                ('numero_assurance', models.CharField(max_length=30)),
                ('date_expiration_assurance', models.DateField()),
                ('date_visite_technique', models.DateField()),
                ('date_expiration_visite', models.DateField()),
                ('numero_licence', models.CharField(blank=True, max_length=30, null=True)),
                ('cooperative', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_exploitation', models.CharField(blank=True, max_length=150, null=True)),
                ('carte_grise_recto', models.ImageField(upload_to='documents/vehicules/')),
                ('carte_grise_verso', models.ImageField(upload_to='documents/vehicules/')),
                ('attestation_assurance', models.FileField(upload_to='documents/vehicules/')),
                ('certificat_visite', models.FileField(upload_to='documents/vehicules/')),
                ('licence_transport', models.FileField(blank=True, null=True, upload_to='documents/vehicules/')),
                ('photo_interieure', models.ImageField(upload_to='photos/vehicules/')),
                ('photo_exterieure', models.ImageField(upload_to='photos/vehicules/')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('suspendu', 'Suspendu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='conducteurs.conducteur')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
    ]
