# Generated by Django 6.0.7 on 2026-08-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('suspendu', 'Suspendu'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20),
        ),
    ]
