# Generated by Django 6.0.7 on 2026-09-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_alter_vehicule_statut_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='photo_exterieure',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='photo_interieure',
        ),
        migrations.CreateModel(
            name='PhotoVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/vehicules/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'Photo du véhicule',
                'verbose_name_plural': 'Photos des véhicules',
                'ordering': ['date_creation'],
            },
        ),
    ]
