# Generated by Django 6.0.7 on 2026-07-24 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='confirmee', max_length=20)),
                ('present_a_bord', models.BooleanField(default=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('point_depose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_depose', to='trajets.pointarret')),
                ('point_ramassage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_ramassage', to='trajets.pointarret')),
                ('siege', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='trajets.siege')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajets.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_passager', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(choices=[('mvola', 'MVola'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money')], max_length=20)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('commission_taux', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_conducteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_escrow', models.CharField(choices=[('en_attente', 'En attente'), ('verse', 'Versé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservations.reservation')),
            ],
        ),
    ]
