# Generated by Django 6.0.7 on 2026-08-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='en_retard',
            field=models.BooleanField(default=False),
        ),
    ]
