# Generated by Django 6.0.7 on 2026-08-09 02:02

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_en_retard'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='beneficiaire_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='beneficiaire_prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='beneficiaire_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='code_billet',
            field=models.CharField(blank=True, default=reservations.models.generer_code_billet, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('soi_meme', 'Pour moi-même'), ('autre_personne', 'Pour une autre personne')], default='soi_meme', max_length=20),
        ),
    ]
