# Generated by Django 6.0.7 on 2026-08-09 02:05

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_beneficiaire_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code_billet',
            field=models.CharField(blank=True, default=reservations.models.generer_code_billet, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
