# Generated by Django 6.0.7 on 2026-08-11 20:02

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_code_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='groupe_reservation',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code_billet',
            field=models.CharField(default=reservations.models.generer_code_billet, editable=False, max_length=20, unique=True),
        ),
    ]
