# Generated by Django 6.0.7 on 2026-08-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_groupe_reservation_and_more'),
        ('trajets', '0003_trajet_lat_arrivee_trajet_lat_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajets.siege'),
        ),
    ]
