# Generated by Django 6.0.7 on 2026-07-24 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteurs', '0003_alter_conducteur_options_conducteur_date_creation_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to='conducteurs.conducteur')),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.reservation')),
            ],
        ),
    ]
